# Generated by Django 6.0 on 2025-12-22 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('iPhone', 'iPhone'), ('MacBook', 'MacBook'), ('iPad', 'iPad'), ('Watch', 'Watch'), ('AirPods', 'AirPods'), ('Huawei', 'Huawei'), ('Dyson', 'Dyson')], max_length=50)),
                ('brand', models.CharField(default='Apple', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('warranty', models.CharField(blank=True, default='', max_length=100)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_gb', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, default='', max_length=80)),
                ('price', models.IntegerField()),
                ('in_stock', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
        ),
    ]
